# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_4.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_instalador_interfaz_4(object):
    def setupUi(self, instalador_interfaz_4):
        instalador_interfaz_4.setObjectName("instalador_interfaz_4")
        instalador_interfaz_4.setEnabled(True)
        instalador_interfaz_4.resize(684, 454)
        instalador_interfaz_4.setMinimumSize(QtCore.QSize(684, 454))
        instalador_interfaz_4.setMaximumSize(QtCore.QSize(684, 454))
        self.facyt_logo = QtWidgets.QLabel(instalador_interfaz_4)
        self.facyt_logo.setGeometry(QtCore.QRect(40, 220, 141, 161))
        self.facyt_logo.setText("")
        self.facyt_logo.setPixmap(QtGui.QPixmap("assets/facyt.png"))
        self.facyt_logo.setScaledContents(True)
        self.facyt_logo.setObjectName("facyt_logo")
        self.uc_logo = QtWidgets.QLabel(instalador_interfaz_4)
        self.uc_logo.setGeometry(QtCore.QRect(50, 40, 111, 161))
        self.uc_logo.setText("")
        self.uc_logo.setPixmap(QtGui.QPixmap("assets/log_uc.png"))
        self.uc_logo.setScaledContents(True)
        self.uc_logo.setObjectName("uc_logo")
        self.layoutWidget = QtWidgets.QWidget(instalador_interfaz_4)
        self.layoutWidget.setGeometry(QtCore.QRect(196, 12, 471, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_principal = QtWidgets.QLabel(self.layoutWidget)
        self.label_principal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_principal.setStyleSheet("font: 63 bold 22pt \"Ubuntu\";")
        self.label_principal.setMidLineWidth(-3)
        self.label_principal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_principal.setWordWrap(True)
        self.label_principal.setObjectName("label_principal")
        self.verticalLayout.addWidget(self.label_principal)
        self.label_descripcion = QtWidgets.QLabel(self.layoutWidget)
        self.label_descripcion.setWordWrap(True)
        self.label_descripcion.setObjectName("label_descripcion")
        self.verticalLayout.addWidget(self.label_descripcion)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.instalacionBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.instalacionBar.setProperty("value", 0)
        self.instalacionBar.setObjectName("instalacionBar")
        self.verticalLayout.addWidget(self.instalacionBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.infor = QtWidgets.QLabel(self.layoutWidget)
        self.infor.setText("")
        self.infor.setObjectName("infor")
        self.verticalLayout.addWidget(self.infor)
        spacerItem2 = QtWidgets.QSpacerItem(20, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.finalizar = QtWidgets.QPushButton(self.layoutWidget)
        self.finalizar.setEnabled(False)
        self.finalizar.setObjectName("finalizar")
        self.horizontalLayout_2.addWidget(self.finalizar)
        spacerItem5 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.cancelar_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelar_4.setObjectName("cancelar_4")
        self.horizontalLayout_2.addWidget(self.cancelar_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(instalador_interfaz_4)
        QtCore.QMetaObject.connectSlotsByName(instalador_interfaz_4)

    def retranslateUi(self, instalador_interfaz_4):
        _translate = QtCore.QCoreApplication.translate
        instalador_interfaz_4.setWindowTitle(_translate("instalador_interfaz_4", "OJ+ Instalador - Instalar"))
        self.label_principal.setText(_translate("instalador_interfaz_4", "Instalación del Juez OJ+"))
        self.label_descripcion.setText(_translate("instalador_interfaz_4", "Inició el proceso de instalación del juez"))
        self.finalizar.setText(_translate("instalador_interfaz_4", "Finalizar"))
        self.cancelar_4.setText(_translate("instalador_interfaz_4", "Cancelar"))